//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.30 at 08:26:12 AM CEST 
//


package com.carerix.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for attachmentsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="attachmentsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CRAttachment" type="{}CRAttachmentType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attachmentsType", propOrder = {
    "crAttachment"
})
public class AttachmentsType {

    @XmlElement(name = "CRAttachment", required = true)
    protected CRAttachmentType crAttachment;

    /**
     * Gets the value of the crAttachment property.
     * 
     * @return
     *     possible object is
     *     {@link CRAttachmentType }
     *     
     */
    public CRAttachmentType getCRAttachment() {
        return crAttachment;
    }

    /**
     * Sets the value of the crAttachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRAttachmentType }
     *     
     */
    public void setCRAttachment(CRAttachmentType value) {
        this.crAttachment = value;
    }

}
