//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.13 at 09:54:33 PM CEST 
//


package com.carerix.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CREmployeeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CREmployeeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="additionalInfo" type="{}additionalInfoType"/>
 *         &lt;element name="adminSyncDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="children" type="{}childrenType"/>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employeeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="externalInfo" type="{}externalInfoType"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="friWorkMinutes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fullAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="homeFullAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hoursPerWeek" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isConfidential" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastContactDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maritalStatus" type="{}maritalStatusType"/>
 *         &lt;element name="matchCountMO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modificationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="monWorkMinutes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="thuWorkMinutes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timesheetTypeKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tueWorkMinutes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wedWorkMinutes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toAdminHomeCountryNode" type="{}toAdminHomeCountryNodeType"/>
 *         &lt;element name="toAdminHomeProvinceNode" type="{}toAdminHomeProvinceNodeType"/>
 *         &lt;element name="toAvailableWithinNode" type="{}toAvailableWithinNodeType"/>
 *         &lt;element name="toBirthCountryNode" type="{}toBirthCountryNodeType"/>
 *         &lt;element name="toBrancheLevel1" type="{}toBrancheLevel1Type"/>
 *         &lt;element name="toBrancheLevel2" type="{}toBrancheLevel2Type"/>
 *         &lt;element name="toCategoryNode" type="{}toCategoryNodeType"/>
 *         &lt;element name="toContractTypeNode" type="{}toContractTypeNodeType"/>
 *         &lt;element name="toCountryNode" type="{}toCountryNodeType"/>
 *         &lt;element name="toCurrentSalaryCurrencyNode" type="{}toCurrentSalaryCurrencyNodeType"/>
 *         &lt;element name="toCurrentSalaryPeriodNode" type="{}toCurrentSalaryPeriodNodeType"/>
 *         &lt;element name="toCurrentSalaryUnitNode" type="{}toCurrentSalaryUnitNodeType"/>
 *         &lt;element name="toDriverLicenceNode" type="{}toDriverLicenceNodeType"/>
 *         &lt;element name="toExperienceNode" type="{}toExperienceNodeType"/>
 *         &lt;element name="toFunction1Level1Node" type="{}toFunction1Level1NodeType"/>
 *         &lt;element name="toFunction1Level2Node" type="{}toFunction1Level2NodeType"/>
 *         &lt;element name="toFunction2Level1Node" type="{}toFunction2Level1NodeType"/>
 *         &lt;element name="toFunction2Level2Node" type="{}toFunction2Level2NodeType"/>
 *         &lt;element name="toFunction3Level1Node" type="{}toFunction3Level1NodeType"/>
 *         &lt;element name="toFunction3Level2Node" type="{}toFunction3Level2NodeType"/>
 *         &lt;element name="toGenderNode" type="{}toGenderNodeType"/>
 *         &lt;element name="toHomeCountryNode" type="{}toHomeCountryNodeType"/>
 *         &lt;element name="toHomeProvinceNode" type="{}toHomeProvinceNodeType"/>
 *         &lt;element name="toIdentificationCountryNode" type="{}toIdentificationCountryNodeType"/>
 *         &lt;element name="toIdentificationTypeNode" type="{}toIdentificationTypeNodeType"/>
 *         &lt;element name="toLanguageNode" type="{}toLanguageNodeType"/>
 *         &lt;element name="toLevel1Function1" type="{}toLevel1Function1Type"/>
 *         &lt;element name="toLevel1Function2" type="{}toLevel1Function2Type"/>
 *         &lt;element name="toLevel1Function3" type="{}toLevel1Function3Type"/>
 *         &lt;element name="toLevel2Function1" type="{}toLevel2Function1Type"/>
 *         &lt;element name="toLevel2Function2" type="{}toLevel2Function2Type"/>
 *         &lt;element name="toLevel2Function3" type="{}toLevel2Function3Type"/>
 *         &lt;element name="toMaritalStatusNode" type="{}toMaritalStatusNodeType"/>
 *         &lt;element name="toMeansOfTransportNode" type="{}toMeansOfTransportNodeType"/>
 *         &lt;element name="toMedicalInsuranceAgencyNode" type="{}toMedicalInsuranceAgencyNodeType"/>
 *         &lt;element name="toMedicalInsuranceCompanyNode" type="{}toMedicalInsuranceCompanyNodeType"/>
 *         &lt;element name="toMedicalInsuranceTypeNode" type="{}toMedicalInsuranceTypeNodeType"/>
 *         &lt;element name="toMinSalaryCurrencyNode" type="{}toMinSalaryCurrencyNodeType"/>
 *         &lt;element name="toMinSalaryPeriodNode" type="{}toMinSalaryPeriodNodeType"/>
 *         &lt;element name="toMinSalaryUnitNode" type="{}toMinSalaryUnitNodeType"/>
 *         &lt;element name="toNationalityNode" type="{}toNationalityNodeType"/>
 *         &lt;element name="toOptional1Node" type="{}toOptional1NodeType"/>
 *         &lt;element name="toPaymentModeNode" type="{}toPaymentModeNodeType"/>
 *         &lt;element name="toPrefBranche1Level1Node" type="{}toPrefBranche1Level1NodeType"/>
 *         &lt;element name="toPrefBranche1Level2Node" type="{}toPrefBranche1Level2NodeType"/>
 *         &lt;element name="toPrefBranche2Level1Node" type="{}toPrefBranche2Level1NodeType"/>
 *         &lt;element name="toPrefBranche2Level2Node" type="{}toPrefBranche2Level2NodeType"/>
 *         &lt;element name="toPrefBranche3Level1Node" type="{}toPrefBranche3Level1NodeType"/>
 *         &lt;element name="toPrefBranche3Level2Node" type="{}toPrefBranche3Level2NodeType"/>
 *         &lt;element name="toPrefContractTypeNode" type="{}toPrefContractTypeNodeType"/>
 *         &lt;element name="toPrefCountry1Node" type="{}toPrefCountry1NodeType"/>
 *         &lt;element name="toPrefCountry2Node" type="{}toPrefCountry2NodeType"/>
 *         &lt;element name="toPrefCountry3Node" type="{}toPrefCountry3NodeType"/>
 *         &lt;element name="toPrefRegion1Node" type="{}toPrefRegion1NodeType"/>
 *         &lt;element name="toPrefRegion2Node" type="{}toPrefRegion2NodeType"/>
 *         &lt;element name="toPrefRegion3Node" type="{}toPrefRegion3NodeType"/>
 *         &lt;element name="toProductNode" type="{}toProductNodeType"/>
 *         &lt;element name="toProductType1Node" type="{}toProductType1NodeType"/>
 *         &lt;element name="toProductType2Node" type="{}toProductType2NodeType"/>
 *         &lt;element name="toProductType3Node" type="{}toProductType3NodeType"/>
 *         &lt;element name="toProductTypeNode1" type="{}toProductTypeNode1Type"/>
 *         &lt;element name="toProductTypeNode2" type="{}toProductTypeNode2Type"/>
 *         &lt;element name="toProductTypeNode3" type="{}toProductTypeNode3Type"/>
 *         &lt;element name="toProvinceNode" type="{}toProvinceNodeType"/>
 *         &lt;element name="toSalaryScaleLevel1Node" type="{}toSalaryScaleLevel1NodeType"/>
 *         &lt;element name="toSalaryScaleLevel2Node" type="{}toSalaryScaleLevel2NodeType"/>
 *         &lt;element name="toStatusNode" type="{}toStatusNodeType"/>
 *         &lt;element name="toUser" type="{}toUserType"/>
 *         &lt;element name="toWorkLevelNode" type="{}toWorkLevelNodeType"/>
 *         &lt;element name="toWorkUnitNode" type="{}toWorkUnitNodeType"/>
 *         &lt;element name="stableHash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CREmployeeType", propOrder = {
    "additionalInfo",
    "adminSyncDate",
    "children",
    "creationDate",
    "deleted",
    "employeeID",
    "externalInfo",
    "firstName",
    "flags",
    "friWorkMinutes",
    "fullAddress",
    "homeFullAddress",
    "hoursPerWeek",
    "isConfidential",
    "lastContactDate",
    "lastName",
    "maritalStatus",
    "matchCountMO",
    "modificationDate",
    "monWorkMinutes",
    "thuWorkMinutes",
    "timesheetTypeKey",
    "tueWorkMinutes",
    "wedWorkMinutes",
    "toAdminHomeCountryNode",
    "toAdminHomeProvinceNode",
    "toAvailableWithinNode",
    "toBirthCountryNode",
    "toBrancheLevel1",
    "toBrancheLevel2",
    "toCategoryNode",
    "toContractTypeNode",
    "toCountryNode",
    "toCurrentSalaryCurrencyNode",
    "toCurrentSalaryPeriodNode",
    "toCurrentSalaryUnitNode",
    "toDriverLicenceNode",
    "toExperienceNode",
    "toFunction1Level1Node",
    "toFunction1Level2Node",
    "toFunction2Level1Node",
    "toFunction2Level2Node",
    "toFunction3Level1Node",
    "toFunction3Level2Node",
    "toGenderNode",
    "toHomeCountryNode",
    "toHomeProvinceNode",
    "toIdentificationCountryNode",
    "toIdentificationTypeNode",
    "toLanguageNode",
    "toLevel1Function1",
    "toLevel1Function2",
    "toLevel1Function3",
    "toLevel2Function1",
    "toLevel2Function2",
    "toLevel2Function3",
    "toMaritalStatusNode",
    "toMeansOfTransportNode",
    "toMedicalInsuranceAgencyNode",
    "toMedicalInsuranceCompanyNode",
    "toMedicalInsuranceTypeNode",
    "toMinSalaryCurrencyNode",
    "toMinSalaryPeriodNode",
    "toMinSalaryUnitNode",
    "toNationalityNode",
    "toOptional1Node",
    "toPaymentModeNode",
    "toPrefBranche1Level1Node",
    "toPrefBranche1Level2Node",
    "toPrefBranche2Level1Node",
    "toPrefBranche2Level2Node",
    "toPrefBranche3Level1Node",
    "toPrefBranche3Level2Node",
    "toPrefContractTypeNode",
    "toPrefCountry1Node",
    "toPrefCountry2Node",
    "toPrefCountry3Node",
    "toPrefRegion1Node",
    "toPrefRegion2Node",
    "toPrefRegion3Node",
    "toProductNode",
    "toProductType1Node",
    "toProductType2Node",
    "toProductType3Node",
    "toProductTypeNode1",
    "toProductTypeNode2",
    "toProductTypeNode3",
    "toProvinceNode",
    "toSalaryScaleLevel1Node",
    "toSalaryScaleLevel2Node",
    "toStatusNode",
    "toUser",
    "toWorkLevelNode",
    "toWorkUnitNode",
    "stableHash"
})
public class CREmployeeType {

    @XmlElement(required = true)
    protected AdditionalInfoType additionalInfo;
    @XmlElement(required = true)
    protected String adminSyncDate;
    @XmlElement(required = true)
    protected ChildrenType children;
    @XmlElement(required = true)
    protected String creationDate;
    @XmlElement(required = true)
    protected String deleted;
    @XmlElement(required = true)
    protected String employeeID;
    @XmlElement(required = true)
    protected ExternalInfoType externalInfo;
    @XmlElement(required = true)
    protected String firstName;
    @XmlElement(required = true)
    protected String flags;
    @XmlElement(required = true)
    protected String friWorkMinutes;
    @XmlElement(required = true)
    protected String fullAddress;
    @XmlElement(required = true)
    protected String homeFullAddress;
    @XmlElement(required = true)
    protected String hoursPerWeek;
    @XmlElement(required = true)
    protected String isConfidential;
    @XmlElement(required = true)
    protected String lastContactDate;
    @XmlElement(required = true)
    protected String lastName;
    @XmlElement(required = true)
    protected MaritalStatusType maritalStatus;
    @XmlElement(required = true)
    protected String matchCountMO;
    @XmlElement(required = true)
    protected String modificationDate;
    @XmlElement(required = true)
    protected String monWorkMinutes;
    @XmlElement(required = true)
    protected String thuWorkMinutes;
    @XmlElement(required = true)
    protected String timesheetTypeKey;
    @XmlElement(required = true)
    protected String tueWorkMinutes;
    @XmlElement(required = true)
    protected String wedWorkMinutes;
    @XmlElement(required = true)
    protected ToAdminHomeCountryNodeType toAdminHomeCountryNode;
    @XmlElement(required = true)
    protected ToAdminHomeProvinceNodeType toAdminHomeProvinceNode;
    @XmlElement(required = true)
    protected ToAvailableWithinNodeType toAvailableWithinNode;
    @XmlElement(required = true)
    protected ToBirthCountryNodeType toBirthCountryNode;
    @XmlElement(required = true)
    protected ToBrancheLevel1Type toBrancheLevel1;
    @XmlElement(required = true)
    protected ToBrancheLevel2Type toBrancheLevel2;
    @XmlElement(required = true)
    protected ToCategoryNodeType toCategoryNode;
    @XmlElement(required = true)
    protected ToContractTypeNodeType toContractTypeNode;
    @XmlElement(required = true)
    protected ToCountryNodeType toCountryNode;
    @XmlElement(required = true)
    protected ToCurrentSalaryCurrencyNodeType toCurrentSalaryCurrencyNode;
    @XmlElement(required = true)
    protected ToCurrentSalaryPeriodNodeType toCurrentSalaryPeriodNode;
    @XmlElement(required = true)
    protected ToCurrentSalaryUnitNodeType toCurrentSalaryUnitNode;
    @XmlElement(required = true)
    protected ToDriverLicenceNodeType toDriverLicenceNode;
    @XmlElement(required = true)
    protected ToExperienceNodeType toExperienceNode;
    @XmlElement(required = true)
    protected ToFunction1Level1NodeType toFunction1Level1Node;
    @XmlElement(required = true)
    protected ToFunction1Level2NodeType toFunction1Level2Node;
    @XmlElement(required = true)
    protected ToFunction2Level1NodeType toFunction2Level1Node;
    @XmlElement(required = true)
    protected ToFunction2Level2NodeType toFunction2Level2Node;
    @XmlElement(required = true)
    protected ToFunction3Level1NodeType toFunction3Level1Node;
    @XmlElement(required = true)
    protected ToFunction3Level2NodeType toFunction3Level2Node;
    @XmlElement(required = true)
    protected ToGenderNodeType toGenderNode;
    @XmlElement(required = true)
    protected ToHomeCountryNodeType toHomeCountryNode;
    @XmlElement(required = true)
    protected ToHomeProvinceNodeType toHomeProvinceNode;
    @XmlElement(required = true)
    protected ToIdentificationCountryNodeType toIdentificationCountryNode;
    @XmlElement(required = true)
    protected ToIdentificationTypeNodeType toIdentificationTypeNode;
    @XmlElement(required = true)
    protected ToLanguageNodeType toLanguageNode;
    @XmlElement(required = true)
    protected ToLevel1Function1Type toLevel1Function1;
    @XmlElement(required = true)
    protected ToLevel1Function2Type toLevel1Function2;
    @XmlElement(required = true)
    protected ToLevel1Function3Type toLevel1Function3;
    @XmlElement(required = true)
    protected ToLevel2Function1Type toLevel2Function1;
    @XmlElement(required = true)
    protected ToLevel2Function2Type toLevel2Function2;
    @XmlElement(required = true)
    protected ToLevel2Function3Type toLevel2Function3;
    @XmlElement(required = true)
    protected ToMaritalStatusNodeType toMaritalStatusNode;
    @XmlElement(required = true)
    protected ToMeansOfTransportNodeType toMeansOfTransportNode;
    @XmlElement(required = true)
    protected ToMedicalInsuranceAgencyNodeType toMedicalInsuranceAgencyNode;
    @XmlElement(required = true)
    protected ToMedicalInsuranceCompanyNodeType toMedicalInsuranceCompanyNode;
    @XmlElement(required = true)
    protected ToMedicalInsuranceTypeNodeType toMedicalInsuranceTypeNode;
    @XmlElement(required = true)
    protected ToMinSalaryCurrencyNodeType toMinSalaryCurrencyNode;
    @XmlElement(required = true)
    protected ToMinSalaryPeriodNodeType toMinSalaryPeriodNode;
    @XmlElement(required = true)
    protected ToMinSalaryUnitNodeType toMinSalaryUnitNode;
    @XmlElement(required = true)
    protected ToNationalityNodeType toNationalityNode;
    @XmlElement(required = true)
    protected ToOptional1NodeType toOptional1Node;
    @XmlElement(required = true)
    protected ToPaymentModeNodeType toPaymentModeNode;
    @XmlElement(required = true)
    protected ToPrefBranche1Level1NodeType toPrefBranche1Level1Node;
    @XmlElement(required = true)
    protected ToPrefBranche1Level2NodeType toPrefBranche1Level2Node;
    @XmlElement(required = true)
    protected ToPrefBranche2Level1NodeType toPrefBranche2Level1Node;
    @XmlElement(required = true)
    protected ToPrefBranche2Level2NodeType toPrefBranche2Level2Node;
    @XmlElement(required = true)
    protected ToPrefBranche3Level1NodeType toPrefBranche3Level1Node;
    @XmlElement(required = true)
    protected ToPrefBranche3Level2NodeType toPrefBranche3Level2Node;
    @XmlElement(required = true)
    protected ToPrefContractTypeNodeType toPrefContractTypeNode;
    @XmlElement(required = true)
    protected ToPrefCountry1NodeType toPrefCountry1Node;
    @XmlElement(required = true)
    protected ToPrefCountry2NodeType toPrefCountry2Node;
    @XmlElement(required = true)
    protected ToPrefCountry3NodeType toPrefCountry3Node;
    @XmlElement(required = true)
    protected ToPrefRegion1NodeType toPrefRegion1Node;
    @XmlElement(required = true)
    protected ToPrefRegion2NodeType toPrefRegion2Node;
    @XmlElement(required = true)
    protected ToPrefRegion3NodeType toPrefRegion3Node;
    @XmlElement(required = true)
    protected ToProductNodeType toProductNode;
    @XmlElement(required = true)
    protected ToProductType1NodeType toProductType1Node;
    @XmlElement(required = true)
    protected ToProductType2NodeType toProductType2Node;
    @XmlElement(required = true)
    protected ToProductType3NodeType toProductType3Node;
    @XmlElement(required = true)
    protected ToProductTypeNode1Type toProductTypeNode1;
    @XmlElement(required = true)
    protected ToProductTypeNode2Type toProductTypeNode2;
    @XmlElement(required = true)
    protected ToProductTypeNode3Type toProductTypeNode3;
    @XmlElement(required = true)
    protected ToProvinceNodeType toProvinceNode;
    @XmlElement(required = true)
    protected ToSalaryScaleLevel1NodeType toSalaryScaleLevel1Node;
    @XmlElement(required = true)
    protected ToSalaryScaleLevel2NodeType toSalaryScaleLevel2Node;
    @XmlElement(required = true)
    protected ToStatusNodeType toStatusNode;
    @XmlElement(required = true)
    protected ToUserType toUser;
    @XmlElement(required = true)
    protected ToWorkLevelNodeType toWorkLevelNode;
    @XmlElement(required = true)
    protected ToWorkUnitNodeType toWorkUnitNode;
    @XmlElement(required = true)
    protected String stableHash;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInfoType }
     *     
     */
    public AdditionalInfoType getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInfoType }
     *     
     */
    public void setAdditionalInfo(AdditionalInfoType value) {
        this.additionalInfo = value;
    }

    /**
     * Gets the value of the adminSyncDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminSyncDate() {
        return adminSyncDate;
    }

    /**
     * Sets the value of the adminSyncDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminSyncDate(String value) {
        this.adminSyncDate = value;
    }

    /**
     * Gets the value of the children property.
     * 
     * @return
     *     possible object is
     *     {@link ChildrenType }
     *     
     */
    public ChildrenType getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildrenType }
     *     
     */
    public void setChildren(ChildrenType value) {
        this.children = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDate(String value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleted(String value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the employeeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeID() {
        return employeeID;
    }

    /**
     * Sets the value of the employeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeID(String value) {
        this.employeeID = value;
    }

    /**
     * Gets the value of the externalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalInfoType }
     *     
     */
    public ExternalInfoType getExternalInfo() {
        return externalInfo;
    }

    /**
     * Sets the value of the externalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalInfoType }
     *     
     */
    public void setExternalInfo(ExternalInfoType value) {
        this.externalInfo = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlags(String value) {
        this.flags = value;
    }

    /**
     * Gets the value of the friWorkMinutes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFriWorkMinutes() {
        return friWorkMinutes;
    }

    /**
     * Sets the value of the friWorkMinutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFriWorkMinutes(String value) {
        this.friWorkMinutes = value;
    }

    /**
     * Gets the value of the fullAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullAddress() {
        return fullAddress;
    }

    /**
     * Sets the value of the fullAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullAddress(String value) {
        this.fullAddress = value;
    }

    /**
     * Gets the value of the homeFullAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeFullAddress() {
        return homeFullAddress;
    }

    /**
     * Sets the value of the homeFullAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeFullAddress(String value) {
        this.homeFullAddress = value;
    }

    /**
     * Gets the value of the hoursPerWeek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoursPerWeek() {
        return hoursPerWeek;
    }

    /**
     * Sets the value of the hoursPerWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoursPerWeek(String value) {
        this.hoursPerWeek = value;
    }

    /**
     * Gets the value of the isConfidential property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsConfidential() {
        return isConfidential;
    }

    /**
     * Sets the value of the isConfidential property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsConfidential(String value) {
        this.isConfidential = value;
    }

    /**
     * Gets the value of the lastContactDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastContactDate() {
        return lastContactDate;
    }

    /**
     * Sets the value of the lastContactDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastContactDate(String value) {
        this.lastContactDate = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link MaritalStatusType }
     *     
     */
    public MaritalStatusType getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaritalStatusType }
     *     
     */
    public void setMaritalStatus(MaritalStatusType value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the matchCountMO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchCountMO() {
        return matchCountMO;
    }

    /**
     * Sets the value of the matchCountMO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchCountMO(String value) {
        this.matchCountMO = value;
    }

    /**
     * Gets the value of the modificationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationDate() {
        return modificationDate;
    }

    /**
     * Sets the value of the modificationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationDate(String value) {
        this.modificationDate = value;
    }

    /**
     * Gets the value of the monWorkMinutes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonWorkMinutes() {
        return monWorkMinutes;
    }

    /**
     * Sets the value of the monWorkMinutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonWorkMinutes(String value) {
        this.monWorkMinutes = value;
    }

    /**
     * Gets the value of the thuWorkMinutes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThuWorkMinutes() {
        return thuWorkMinutes;
    }

    /**
     * Sets the value of the thuWorkMinutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThuWorkMinutes(String value) {
        this.thuWorkMinutes = value;
    }

    /**
     * Gets the value of the timesheetTypeKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimesheetTypeKey() {
        return timesheetTypeKey;
    }

    /**
     * Sets the value of the timesheetTypeKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimesheetTypeKey(String value) {
        this.timesheetTypeKey = value;
    }

    /**
     * Gets the value of the tueWorkMinutes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTueWorkMinutes() {
        return tueWorkMinutes;
    }

    /**
     * Sets the value of the tueWorkMinutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTueWorkMinutes(String value) {
        this.tueWorkMinutes = value;
    }

    /**
     * Gets the value of the wedWorkMinutes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWedWorkMinutes() {
        return wedWorkMinutes;
    }

    /**
     * Sets the value of the wedWorkMinutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWedWorkMinutes(String value) {
        this.wedWorkMinutes = value;
    }

    /**
     * Gets the value of the toAdminHomeCountryNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToAdminHomeCountryNodeType }
     *     
     */
    public ToAdminHomeCountryNodeType getToAdminHomeCountryNode() {
        return toAdminHomeCountryNode;
    }

    /**
     * Sets the value of the toAdminHomeCountryNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToAdminHomeCountryNodeType }
     *     
     */
    public void setToAdminHomeCountryNode(ToAdminHomeCountryNodeType value) {
        this.toAdminHomeCountryNode = value;
    }

    /**
     * Gets the value of the toAdminHomeProvinceNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToAdminHomeProvinceNodeType }
     *     
     */
    public ToAdminHomeProvinceNodeType getToAdminHomeProvinceNode() {
        return toAdminHomeProvinceNode;
    }

    /**
     * Sets the value of the toAdminHomeProvinceNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToAdminHomeProvinceNodeType }
     *     
     */
    public void setToAdminHomeProvinceNode(ToAdminHomeProvinceNodeType value) {
        this.toAdminHomeProvinceNode = value;
    }

    /**
     * Gets the value of the toAvailableWithinNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToAvailableWithinNodeType }
     *     
     */
    public ToAvailableWithinNodeType getToAvailableWithinNode() {
        return toAvailableWithinNode;
    }

    /**
     * Sets the value of the toAvailableWithinNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToAvailableWithinNodeType }
     *     
     */
    public void setToAvailableWithinNode(ToAvailableWithinNodeType value) {
        this.toAvailableWithinNode = value;
    }

    /**
     * Gets the value of the toBirthCountryNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToBirthCountryNodeType }
     *     
     */
    public ToBirthCountryNodeType getToBirthCountryNode() {
        return toBirthCountryNode;
    }

    /**
     * Sets the value of the toBirthCountryNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToBirthCountryNodeType }
     *     
     */
    public void setToBirthCountryNode(ToBirthCountryNodeType value) {
        this.toBirthCountryNode = value;
    }

    /**
     * Gets the value of the toBrancheLevel1 property.
     * 
     * @return
     *     possible object is
     *     {@link ToBrancheLevel1Type }
     *     
     */
    public ToBrancheLevel1Type getToBrancheLevel1() {
        return toBrancheLevel1;
    }

    /**
     * Sets the value of the toBrancheLevel1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToBrancheLevel1Type }
     *     
     */
    public void setToBrancheLevel1(ToBrancheLevel1Type value) {
        this.toBrancheLevel1 = value;
    }

    /**
     * Gets the value of the toBrancheLevel2 property.
     * 
     * @return
     *     possible object is
     *     {@link ToBrancheLevel2Type }
     *     
     */
    public ToBrancheLevel2Type getToBrancheLevel2() {
        return toBrancheLevel2;
    }

    /**
     * Sets the value of the toBrancheLevel2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToBrancheLevel2Type }
     *     
     */
    public void setToBrancheLevel2(ToBrancheLevel2Type value) {
        this.toBrancheLevel2 = value;
    }

    /**
     * Gets the value of the toCategoryNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToCategoryNodeType }
     *     
     */
    public ToCategoryNodeType getToCategoryNode() {
        return toCategoryNode;
    }

    /**
     * Sets the value of the toCategoryNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToCategoryNodeType }
     *     
     */
    public void setToCategoryNode(ToCategoryNodeType value) {
        this.toCategoryNode = value;
    }

    /**
     * Gets the value of the toContractTypeNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToContractTypeNodeType }
     *     
     */
    public ToContractTypeNodeType getToContractTypeNode() {
        return toContractTypeNode;
    }

    /**
     * Sets the value of the toContractTypeNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToContractTypeNodeType }
     *     
     */
    public void setToContractTypeNode(ToContractTypeNodeType value) {
        this.toContractTypeNode = value;
    }

    /**
     * Gets the value of the toCountryNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToCountryNodeType }
     *     
     */
    public ToCountryNodeType getToCountryNode() {
        return toCountryNode;
    }

    /**
     * Sets the value of the toCountryNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToCountryNodeType }
     *     
     */
    public void setToCountryNode(ToCountryNodeType value) {
        this.toCountryNode = value;
    }

    /**
     * Gets the value of the toCurrentSalaryCurrencyNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToCurrentSalaryCurrencyNodeType }
     *     
     */
    public ToCurrentSalaryCurrencyNodeType getToCurrentSalaryCurrencyNode() {
        return toCurrentSalaryCurrencyNode;
    }

    /**
     * Sets the value of the toCurrentSalaryCurrencyNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToCurrentSalaryCurrencyNodeType }
     *     
     */
    public void setToCurrentSalaryCurrencyNode(ToCurrentSalaryCurrencyNodeType value) {
        this.toCurrentSalaryCurrencyNode = value;
    }

    /**
     * Gets the value of the toCurrentSalaryPeriodNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToCurrentSalaryPeriodNodeType }
     *     
     */
    public ToCurrentSalaryPeriodNodeType getToCurrentSalaryPeriodNode() {
        return toCurrentSalaryPeriodNode;
    }

    /**
     * Sets the value of the toCurrentSalaryPeriodNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToCurrentSalaryPeriodNodeType }
     *     
     */
    public void setToCurrentSalaryPeriodNode(ToCurrentSalaryPeriodNodeType value) {
        this.toCurrentSalaryPeriodNode = value;
    }

    /**
     * Gets the value of the toCurrentSalaryUnitNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToCurrentSalaryUnitNodeType }
     *     
     */
    public ToCurrentSalaryUnitNodeType getToCurrentSalaryUnitNode() {
        return toCurrentSalaryUnitNode;
    }

    /**
     * Sets the value of the toCurrentSalaryUnitNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToCurrentSalaryUnitNodeType }
     *     
     */
    public void setToCurrentSalaryUnitNode(ToCurrentSalaryUnitNodeType value) {
        this.toCurrentSalaryUnitNode = value;
    }

    /**
     * Gets the value of the toDriverLicenceNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToDriverLicenceNodeType }
     *     
     */
    public ToDriverLicenceNodeType getToDriverLicenceNode() {
        return toDriverLicenceNode;
    }

    /**
     * Sets the value of the toDriverLicenceNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToDriverLicenceNodeType }
     *     
     */
    public void setToDriverLicenceNode(ToDriverLicenceNodeType value) {
        this.toDriverLicenceNode = value;
    }

    /**
     * Gets the value of the toExperienceNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToExperienceNodeType }
     *     
     */
    public ToExperienceNodeType getToExperienceNode() {
        return toExperienceNode;
    }

    /**
     * Sets the value of the toExperienceNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToExperienceNodeType }
     *     
     */
    public void setToExperienceNode(ToExperienceNodeType value) {
        this.toExperienceNode = value;
    }

    /**
     * Gets the value of the toFunction1Level1Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToFunction1Level1NodeType }
     *     
     */
    public ToFunction1Level1NodeType getToFunction1Level1Node() {
        return toFunction1Level1Node;
    }

    /**
     * Sets the value of the toFunction1Level1Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToFunction1Level1NodeType }
     *     
     */
    public void setToFunction1Level1Node(ToFunction1Level1NodeType value) {
        this.toFunction1Level1Node = value;
    }

    /**
     * Gets the value of the toFunction1Level2Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToFunction1Level2NodeType }
     *     
     */
    public ToFunction1Level2NodeType getToFunction1Level2Node() {
        return toFunction1Level2Node;
    }

    /**
     * Sets the value of the toFunction1Level2Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToFunction1Level2NodeType }
     *     
     */
    public void setToFunction1Level2Node(ToFunction1Level2NodeType value) {
        this.toFunction1Level2Node = value;
    }

    /**
     * Gets the value of the toFunction2Level1Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToFunction2Level1NodeType }
     *     
     */
    public ToFunction2Level1NodeType getToFunction2Level1Node() {
        return toFunction2Level1Node;
    }

    /**
     * Sets the value of the toFunction2Level1Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToFunction2Level1NodeType }
     *     
     */
    public void setToFunction2Level1Node(ToFunction2Level1NodeType value) {
        this.toFunction2Level1Node = value;
    }

    /**
     * Gets the value of the toFunction2Level2Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToFunction2Level2NodeType }
     *     
     */
    public ToFunction2Level2NodeType getToFunction2Level2Node() {
        return toFunction2Level2Node;
    }

    /**
     * Sets the value of the toFunction2Level2Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToFunction2Level2NodeType }
     *     
     */
    public void setToFunction2Level2Node(ToFunction2Level2NodeType value) {
        this.toFunction2Level2Node = value;
    }

    /**
     * Gets the value of the toFunction3Level1Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToFunction3Level1NodeType }
     *     
     */
    public ToFunction3Level1NodeType getToFunction3Level1Node() {
        return toFunction3Level1Node;
    }

    /**
     * Sets the value of the toFunction3Level1Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToFunction3Level1NodeType }
     *     
     */
    public void setToFunction3Level1Node(ToFunction3Level1NodeType value) {
        this.toFunction3Level1Node = value;
    }

    /**
     * Gets the value of the toFunction3Level2Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToFunction3Level2NodeType }
     *     
     */
    public ToFunction3Level2NodeType getToFunction3Level2Node() {
        return toFunction3Level2Node;
    }

    /**
     * Sets the value of the toFunction3Level2Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToFunction3Level2NodeType }
     *     
     */
    public void setToFunction3Level2Node(ToFunction3Level2NodeType value) {
        this.toFunction3Level2Node = value;
    }

    /**
     * Gets the value of the toGenderNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToGenderNodeType }
     *     
     */
    public ToGenderNodeType getToGenderNode() {
        return toGenderNode;
    }

    /**
     * Sets the value of the toGenderNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToGenderNodeType }
     *     
     */
    public void setToGenderNode(ToGenderNodeType value) {
        this.toGenderNode = value;
    }

    /**
     * Gets the value of the toHomeCountryNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToHomeCountryNodeType }
     *     
     */
    public ToHomeCountryNodeType getToHomeCountryNode() {
        return toHomeCountryNode;
    }

    /**
     * Sets the value of the toHomeCountryNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToHomeCountryNodeType }
     *     
     */
    public void setToHomeCountryNode(ToHomeCountryNodeType value) {
        this.toHomeCountryNode = value;
    }

    /**
     * Gets the value of the toHomeProvinceNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToHomeProvinceNodeType }
     *     
     */
    public ToHomeProvinceNodeType getToHomeProvinceNode() {
        return toHomeProvinceNode;
    }

    /**
     * Sets the value of the toHomeProvinceNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToHomeProvinceNodeType }
     *     
     */
    public void setToHomeProvinceNode(ToHomeProvinceNodeType value) {
        this.toHomeProvinceNode = value;
    }

    /**
     * Gets the value of the toIdentificationCountryNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToIdentificationCountryNodeType }
     *     
     */
    public ToIdentificationCountryNodeType getToIdentificationCountryNode() {
        return toIdentificationCountryNode;
    }

    /**
     * Sets the value of the toIdentificationCountryNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToIdentificationCountryNodeType }
     *     
     */
    public void setToIdentificationCountryNode(ToIdentificationCountryNodeType value) {
        this.toIdentificationCountryNode = value;
    }

    /**
     * Gets the value of the toIdentificationTypeNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToIdentificationTypeNodeType }
     *     
     */
    public ToIdentificationTypeNodeType getToIdentificationTypeNode() {
        return toIdentificationTypeNode;
    }

    /**
     * Sets the value of the toIdentificationTypeNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToIdentificationTypeNodeType }
     *     
     */
    public void setToIdentificationTypeNode(ToIdentificationTypeNodeType value) {
        this.toIdentificationTypeNode = value;
    }

    /**
     * Gets the value of the toLanguageNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToLanguageNodeType }
     *     
     */
    public ToLanguageNodeType getToLanguageNode() {
        return toLanguageNode;
    }

    /**
     * Sets the value of the toLanguageNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToLanguageNodeType }
     *     
     */
    public void setToLanguageNode(ToLanguageNodeType value) {
        this.toLanguageNode = value;
    }

    /**
     * Gets the value of the toLevel1Function1 property.
     * 
     * @return
     *     possible object is
     *     {@link ToLevel1Function1Type }
     *     
     */
    public ToLevel1Function1Type getToLevel1Function1() {
        return toLevel1Function1;
    }

    /**
     * Sets the value of the toLevel1Function1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToLevel1Function1Type }
     *     
     */
    public void setToLevel1Function1(ToLevel1Function1Type value) {
        this.toLevel1Function1 = value;
    }

    /**
     * Gets the value of the toLevel1Function2 property.
     * 
     * @return
     *     possible object is
     *     {@link ToLevel1Function2Type }
     *     
     */
    public ToLevel1Function2Type getToLevel1Function2() {
        return toLevel1Function2;
    }

    /**
     * Sets the value of the toLevel1Function2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToLevel1Function2Type }
     *     
     */
    public void setToLevel1Function2(ToLevel1Function2Type value) {
        this.toLevel1Function2 = value;
    }

    /**
     * Gets the value of the toLevel1Function3 property.
     * 
     * @return
     *     possible object is
     *     {@link ToLevel1Function3Type }
     *     
     */
    public ToLevel1Function3Type getToLevel1Function3() {
        return toLevel1Function3;
    }

    /**
     * Sets the value of the toLevel1Function3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToLevel1Function3Type }
     *     
     */
    public void setToLevel1Function3(ToLevel1Function3Type value) {
        this.toLevel1Function3 = value;
    }

    /**
     * Gets the value of the toLevel2Function1 property.
     * 
     * @return
     *     possible object is
     *     {@link ToLevel2Function1Type }
     *     
     */
    public ToLevel2Function1Type getToLevel2Function1() {
        return toLevel2Function1;
    }

    /**
     * Sets the value of the toLevel2Function1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToLevel2Function1Type }
     *     
     */
    public void setToLevel2Function1(ToLevel2Function1Type value) {
        this.toLevel2Function1 = value;
    }

    /**
     * Gets the value of the toLevel2Function2 property.
     * 
     * @return
     *     possible object is
     *     {@link ToLevel2Function2Type }
     *     
     */
    public ToLevel2Function2Type getToLevel2Function2() {
        return toLevel2Function2;
    }

    /**
     * Sets the value of the toLevel2Function2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToLevel2Function2Type }
     *     
     */
    public void setToLevel2Function2(ToLevel2Function2Type value) {
        this.toLevel2Function2 = value;
    }

    /**
     * Gets the value of the toLevel2Function3 property.
     * 
     * @return
     *     possible object is
     *     {@link ToLevel2Function3Type }
     *     
     */
    public ToLevel2Function3Type getToLevel2Function3() {
        return toLevel2Function3;
    }

    /**
     * Sets the value of the toLevel2Function3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToLevel2Function3Type }
     *     
     */
    public void setToLevel2Function3(ToLevel2Function3Type value) {
        this.toLevel2Function3 = value;
    }

    /**
     * Gets the value of the toMaritalStatusNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToMaritalStatusNodeType }
     *     
     */
    public ToMaritalStatusNodeType getToMaritalStatusNode() {
        return toMaritalStatusNode;
    }

    /**
     * Sets the value of the toMaritalStatusNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToMaritalStatusNodeType }
     *     
     */
    public void setToMaritalStatusNode(ToMaritalStatusNodeType value) {
        this.toMaritalStatusNode = value;
    }

    /**
     * Gets the value of the toMeansOfTransportNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToMeansOfTransportNodeType }
     *     
     */
    public ToMeansOfTransportNodeType getToMeansOfTransportNode() {
        return toMeansOfTransportNode;
    }

    /**
     * Sets the value of the toMeansOfTransportNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToMeansOfTransportNodeType }
     *     
     */
    public void setToMeansOfTransportNode(ToMeansOfTransportNodeType value) {
        this.toMeansOfTransportNode = value;
    }

    /**
     * Gets the value of the toMedicalInsuranceAgencyNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToMedicalInsuranceAgencyNodeType }
     *     
     */
    public ToMedicalInsuranceAgencyNodeType getToMedicalInsuranceAgencyNode() {
        return toMedicalInsuranceAgencyNode;
    }

    /**
     * Sets the value of the toMedicalInsuranceAgencyNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToMedicalInsuranceAgencyNodeType }
     *     
     */
    public void setToMedicalInsuranceAgencyNode(ToMedicalInsuranceAgencyNodeType value) {
        this.toMedicalInsuranceAgencyNode = value;
    }

    /**
     * Gets the value of the toMedicalInsuranceCompanyNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToMedicalInsuranceCompanyNodeType }
     *     
     */
    public ToMedicalInsuranceCompanyNodeType getToMedicalInsuranceCompanyNode() {
        return toMedicalInsuranceCompanyNode;
    }

    /**
     * Sets the value of the toMedicalInsuranceCompanyNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToMedicalInsuranceCompanyNodeType }
     *     
     */
    public void setToMedicalInsuranceCompanyNode(ToMedicalInsuranceCompanyNodeType value) {
        this.toMedicalInsuranceCompanyNode = value;
    }

    /**
     * Gets the value of the toMedicalInsuranceTypeNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToMedicalInsuranceTypeNodeType }
     *     
     */
    public ToMedicalInsuranceTypeNodeType getToMedicalInsuranceTypeNode() {
        return toMedicalInsuranceTypeNode;
    }

    /**
     * Sets the value of the toMedicalInsuranceTypeNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToMedicalInsuranceTypeNodeType }
     *     
     */
    public void setToMedicalInsuranceTypeNode(ToMedicalInsuranceTypeNodeType value) {
        this.toMedicalInsuranceTypeNode = value;
    }

    /**
     * Gets the value of the toMinSalaryCurrencyNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToMinSalaryCurrencyNodeType }
     *     
     */
    public ToMinSalaryCurrencyNodeType getToMinSalaryCurrencyNode() {
        return toMinSalaryCurrencyNode;
    }

    /**
     * Sets the value of the toMinSalaryCurrencyNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToMinSalaryCurrencyNodeType }
     *     
     */
    public void setToMinSalaryCurrencyNode(ToMinSalaryCurrencyNodeType value) {
        this.toMinSalaryCurrencyNode = value;
    }

    /**
     * Gets the value of the toMinSalaryPeriodNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToMinSalaryPeriodNodeType }
     *     
     */
    public ToMinSalaryPeriodNodeType getToMinSalaryPeriodNode() {
        return toMinSalaryPeriodNode;
    }

    /**
     * Sets the value of the toMinSalaryPeriodNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToMinSalaryPeriodNodeType }
     *     
     */
    public void setToMinSalaryPeriodNode(ToMinSalaryPeriodNodeType value) {
        this.toMinSalaryPeriodNode = value;
    }

    /**
     * Gets the value of the toMinSalaryUnitNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToMinSalaryUnitNodeType }
     *     
     */
    public ToMinSalaryUnitNodeType getToMinSalaryUnitNode() {
        return toMinSalaryUnitNode;
    }

    /**
     * Sets the value of the toMinSalaryUnitNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToMinSalaryUnitNodeType }
     *     
     */
    public void setToMinSalaryUnitNode(ToMinSalaryUnitNodeType value) {
        this.toMinSalaryUnitNode = value;
    }

    /**
     * Gets the value of the toNationalityNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToNationalityNodeType }
     *     
     */
    public ToNationalityNodeType getToNationalityNode() {
        return toNationalityNode;
    }

    /**
     * Sets the value of the toNationalityNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToNationalityNodeType }
     *     
     */
    public void setToNationalityNode(ToNationalityNodeType value) {
        this.toNationalityNode = value;
    }

    /**
     * Gets the value of the toOptional1Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToOptional1NodeType }
     *     
     */
    public ToOptional1NodeType getToOptional1Node() {
        return toOptional1Node;
    }

    /**
     * Sets the value of the toOptional1Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToOptional1NodeType }
     *     
     */
    public void setToOptional1Node(ToOptional1NodeType value) {
        this.toOptional1Node = value;
    }

    /**
     * Gets the value of the toPaymentModeNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToPaymentModeNodeType }
     *     
     */
    public ToPaymentModeNodeType getToPaymentModeNode() {
        return toPaymentModeNode;
    }

    /**
     * Sets the value of the toPaymentModeNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPaymentModeNodeType }
     *     
     */
    public void setToPaymentModeNode(ToPaymentModeNodeType value) {
        this.toPaymentModeNode = value;
    }

    /**
     * Gets the value of the toPrefBranche1Level1Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefBranche1Level1NodeType }
     *     
     */
    public ToPrefBranche1Level1NodeType getToPrefBranche1Level1Node() {
        return toPrefBranche1Level1Node;
    }

    /**
     * Sets the value of the toPrefBranche1Level1Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefBranche1Level1NodeType }
     *     
     */
    public void setToPrefBranche1Level1Node(ToPrefBranche1Level1NodeType value) {
        this.toPrefBranche1Level1Node = value;
    }

    /**
     * Gets the value of the toPrefBranche1Level2Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefBranche1Level2NodeType }
     *     
     */
    public ToPrefBranche1Level2NodeType getToPrefBranche1Level2Node() {
        return toPrefBranche1Level2Node;
    }

    /**
     * Sets the value of the toPrefBranche1Level2Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefBranche1Level2NodeType }
     *     
     */
    public void setToPrefBranche1Level2Node(ToPrefBranche1Level2NodeType value) {
        this.toPrefBranche1Level2Node = value;
    }

    /**
     * Gets the value of the toPrefBranche2Level1Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefBranche2Level1NodeType }
     *     
     */
    public ToPrefBranche2Level1NodeType getToPrefBranche2Level1Node() {
        return toPrefBranche2Level1Node;
    }

    /**
     * Sets the value of the toPrefBranche2Level1Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefBranche2Level1NodeType }
     *     
     */
    public void setToPrefBranche2Level1Node(ToPrefBranche2Level1NodeType value) {
        this.toPrefBranche2Level1Node = value;
    }

    /**
     * Gets the value of the toPrefBranche2Level2Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefBranche2Level2NodeType }
     *     
     */
    public ToPrefBranche2Level2NodeType getToPrefBranche2Level2Node() {
        return toPrefBranche2Level2Node;
    }

    /**
     * Sets the value of the toPrefBranche2Level2Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefBranche2Level2NodeType }
     *     
     */
    public void setToPrefBranche2Level2Node(ToPrefBranche2Level2NodeType value) {
        this.toPrefBranche2Level2Node = value;
    }

    /**
     * Gets the value of the toPrefBranche3Level1Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefBranche3Level1NodeType }
     *     
     */
    public ToPrefBranche3Level1NodeType getToPrefBranche3Level1Node() {
        return toPrefBranche3Level1Node;
    }

    /**
     * Sets the value of the toPrefBranche3Level1Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefBranche3Level1NodeType }
     *     
     */
    public void setToPrefBranche3Level1Node(ToPrefBranche3Level1NodeType value) {
        this.toPrefBranche3Level1Node = value;
    }

    /**
     * Gets the value of the toPrefBranche3Level2Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefBranche3Level2NodeType }
     *     
     */
    public ToPrefBranche3Level2NodeType getToPrefBranche3Level2Node() {
        return toPrefBranche3Level2Node;
    }

    /**
     * Sets the value of the toPrefBranche3Level2Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefBranche3Level2NodeType }
     *     
     */
    public void setToPrefBranche3Level2Node(ToPrefBranche3Level2NodeType value) {
        this.toPrefBranche3Level2Node = value;
    }

    /**
     * Gets the value of the toPrefContractTypeNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefContractTypeNodeType }
     *     
     */
    public ToPrefContractTypeNodeType getToPrefContractTypeNode() {
        return toPrefContractTypeNode;
    }

    /**
     * Sets the value of the toPrefContractTypeNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefContractTypeNodeType }
     *     
     */
    public void setToPrefContractTypeNode(ToPrefContractTypeNodeType value) {
        this.toPrefContractTypeNode = value;
    }

    /**
     * Gets the value of the toPrefCountry1Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefCountry1NodeType }
     *     
     */
    public ToPrefCountry1NodeType getToPrefCountry1Node() {
        return toPrefCountry1Node;
    }

    /**
     * Sets the value of the toPrefCountry1Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefCountry1NodeType }
     *     
     */
    public void setToPrefCountry1Node(ToPrefCountry1NodeType value) {
        this.toPrefCountry1Node = value;
    }

    /**
     * Gets the value of the toPrefCountry2Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefCountry2NodeType }
     *     
     */
    public ToPrefCountry2NodeType getToPrefCountry2Node() {
        return toPrefCountry2Node;
    }

    /**
     * Sets the value of the toPrefCountry2Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefCountry2NodeType }
     *     
     */
    public void setToPrefCountry2Node(ToPrefCountry2NodeType value) {
        this.toPrefCountry2Node = value;
    }

    /**
     * Gets the value of the toPrefCountry3Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefCountry3NodeType }
     *     
     */
    public ToPrefCountry3NodeType getToPrefCountry3Node() {
        return toPrefCountry3Node;
    }

    /**
     * Sets the value of the toPrefCountry3Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefCountry3NodeType }
     *     
     */
    public void setToPrefCountry3Node(ToPrefCountry3NodeType value) {
        this.toPrefCountry3Node = value;
    }

    /**
     * Gets the value of the toPrefRegion1Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefRegion1NodeType }
     *     
     */
    public ToPrefRegion1NodeType getToPrefRegion1Node() {
        return toPrefRegion1Node;
    }

    /**
     * Sets the value of the toPrefRegion1Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefRegion1NodeType }
     *     
     */
    public void setToPrefRegion1Node(ToPrefRegion1NodeType value) {
        this.toPrefRegion1Node = value;
    }

    /**
     * Gets the value of the toPrefRegion2Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefRegion2NodeType }
     *     
     */
    public ToPrefRegion2NodeType getToPrefRegion2Node() {
        return toPrefRegion2Node;
    }

    /**
     * Sets the value of the toPrefRegion2Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefRegion2NodeType }
     *     
     */
    public void setToPrefRegion2Node(ToPrefRegion2NodeType value) {
        this.toPrefRegion2Node = value;
    }

    /**
     * Gets the value of the toPrefRegion3Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToPrefRegion3NodeType }
     *     
     */
    public ToPrefRegion3NodeType getToPrefRegion3Node() {
        return toPrefRegion3Node;
    }

    /**
     * Sets the value of the toPrefRegion3Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPrefRegion3NodeType }
     *     
     */
    public void setToPrefRegion3Node(ToPrefRegion3NodeType value) {
        this.toPrefRegion3Node = value;
    }

    /**
     * Gets the value of the toProductNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToProductNodeType }
     *     
     */
    public ToProductNodeType getToProductNode() {
        return toProductNode;
    }

    /**
     * Sets the value of the toProductNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToProductNodeType }
     *     
     */
    public void setToProductNode(ToProductNodeType value) {
        this.toProductNode = value;
    }

    /**
     * Gets the value of the toProductType1Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToProductType1NodeType }
     *     
     */
    public ToProductType1NodeType getToProductType1Node() {
        return toProductType1Node;
    }

    /**
     * Sets the value of the toProductType1Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToProductType1NodeType }
     *     
     */
    public void setToProductType1Node(ToProductType1NodeType value) {
        this.toProductType1Node = value;
    }

    /**
     * Gets the value of the toProductType2Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToProductType2NodeType }
     *     
     */
    public ToProductType2NodeType getToProductType2Node() {
        return toProductType2Node;
    }

    /**
     * Sets the value of the toProductType2Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToProductType2NodeType }
     *     
     */
    public void setToProductType2Node(ToProductType2NodeType value) {
        this.toProductType2Node = value;
    }

    /**
     * Gets the value of the toProductType3Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToProductType3NodeType }
     *     
     */
    public ToProductType3NodeType getToProductType3Node() {
        return toProductType3Node;
    }

    /**
     * Sets the value of the toProductType3Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToProductType3NodeType }
     *     
     */
    public void setToProductType3Node(ToProductType3NodeType value) {
        this.toProductType3Node = value;
    }

    /**
     * Gets the value of the toProductTypeNode1 property.
     * 
     * @return
     *     possible object is
     *     {@link ToProductTypeNode1Type }
     *     
     */
    public ToProductTypeNode1Type getToProductTypeNode1() {
        return toProductTypeNode1;
    }

    /**
     * Sets the value of the toProductTypeNode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToProductTypeNode1Type }
     *     
     */
    public void setToProductTypeNode1(ToProductTypeNode1Type value) {
        this.toProductTypeNode1 = value;
    }

    /**
     * Gets the value of the toProductTypeNode2 property.
     * 
     * @return
     *     possible object is
     *     {@link ToProductTypeNode2Type }
     *     
     */
    public ToProductTypeNode2Type getToProductTypeNode2() {
        return toProductTypeNode2;
    }

    /**
     * Sets the value of the toProductTypeNode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToProductTypeNode2Type }
     *     
     */
    public void setToProductTypeNode2(ToProductTypeNode2Type value) {
        this.toProductTypeNode2 = value;
    }

    /**
     * Gets the value of the toProductTypeNode3 property.
     * 
     * @return
     *     possible object is
     *     {@link ToProductTypeNode3Type }
     *     
     */
    public ToProductTypeNode3Type getToProductTypeNode3() {
        return toProductTypeNode3;
    }

    /**
     * Sets the value of the toProductTypeNode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToProductTypeNode3Type }
     *     
     */
    public void setToProductTypeNode3(ToProductTypeNode3Type value) {
        this.toProductTypeNode3 = value;
    }

    /**
     * Gets the value of the toProvinceNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToProvinceNodeType }
     *     
     */
    public ToProvinceNodeType getToProvinceNode() {
        return toProvinceNode;
    }

    /**
     * Sets the value of the toProvinceNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToProvinceNodeType }
     *     
     */
    public void setToProvinceNode(ToProvinceNodeType value) {
        this.toProvinceNode = value;
    }

    /**
     * Gets the value of the toSalaryScaleLevel1Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToSalaryScaleLevel1NodeType }
     *     
     */
    public ToSalaryScaleLevel1NodeType getToSalaryScaleLevel1Node() {
        return toSalaryScaleLevel1Node;
    }

    /**
     * Sets the value of the toSalaryScaleLevel1Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToSalaryScaleLevel1NodeType }
     *     
     */
    public void setToSalaryScaleLevel1Node(ToSalaryScaleLevel1NodeType value) {
        this.toSalaryScaleLevel1Node = value;
    }

    /**
     * Gets the value of the toSalaryScaleLevel2Node property.
     * 
     * @return
     *     possible object is
     *     {@link ToSalaryScaleLevel2NodeType }
     *     
     */
    public ToSalaryScaleLevel2NodeType getToSalaryScaleLevel2Node() {
        return toSalaryScaleLevel2Node;
    }

    /**
     * Sets the value of the toSalaryScaleLevel2Node property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToSalaryScaleLevel2NodeType }
     *     
     */
    public void setToSalaryScaleLevel2Node(ToSalaryScaleLevel2NodeType value) {
        this.toSalaryScaleLevel2Node = value;
    }

    /**
     * Gets the value of the toStatusNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToStatusNodeType }
     *     
     */
    public ToStatusNodeType getToStatusNode() {
        return toStatusNode;
    }

    /**
     * Sets the value of the toStatusNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToStatusNodeType }
     *     
     */
    public void setToStatusNode(ToStatusNodeType value) {
        this.toStatusNode = value;
    }

    /**
     * Gets the value of the toUser property.
     * 
     * @return
     *     possible object is
     *     {@link ToUserType }
     *     
     */
    public ToUserType getToUser() {
        return toUser;
    }

    /**
     * Sets the value of the toUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToUserType }
     *     
     */
    public void setToUser(ToUserType value) {
        this.toUser = value;
    }

    /**
     * Gets the value of the toWorkLevelNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToWorkLevelNodeType }
     *     
     */
    public ToWorkLevelNodeType getToWorkLevelNode() {
        return toWorkLevelNode;
    }

    /**
     * Sets the value of the toWorkLevelNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToWorkLevelNodeType }
     *     
     */
    public void setToWorkLevelNode(ToWorkLevelNodeType value) {
        this.toWorkLevelNode = value;
    }

    /**
     * Gets the value of the toWorkUnitNode property.
     * 
     * @return
     *     possible object is
     *     {@link ToWorkUnitNodeType }
     *     
     */
    public ToWorkUnitNodeType getToWorkUnitNode() {
        return toWorkUnitNode;
    }

    /**
     * Sets the value of the toWorkUnitNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToWorkUnitNodeType }
     *     
     */
    public void setToWorkUnitNode(ToWorkUnitNodeType value) {
        this.toWorkUnitNode = value;
    }

    /**
     * Gets the value of the stableHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStableHash() {
        return stableHash;
    }

    /**
     * Sets the value of the stableHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStableHash(String value) {
        this.stableHash = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
