//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.30 at 08:54:44 PM CEST 
//


package com.carerix.api;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CRUserType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CRUserType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="additionalInfo" type="{}additionalInfoType" minOccurs="0"/>
 *         &lt;element name="addressUseCompanyMailingAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="birthDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailAddressPrivate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailNotificationPopup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="forwardEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="goals" type="{}goalsType" minOccurs="0"/>
 *         &lt;element name="homeCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="homeFullAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="homeNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="homePostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="homeStreet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="initials" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isActive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isEmailInConfidential" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isEmailOutConfidential" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isLoginBlocked" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isMasterUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isNewUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isTbaActive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isTokenHomeActive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isTokenRoadActive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isTokenWorkActive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jobTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastContactDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mailboxFlags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mailboxSettings" type="{}mailboxSettingsType" minOccurs="0"/>
 *         &lt;element name="mobileNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modificationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="previewDelay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userBonuses" type="{}userBonusesType" minOccurs="0"/>
 *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="visitAddressUseCompanyVisitAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="wantsCookie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modifiedBy" type="{}modifiedByType" minOccurs="0"/>
 *         &lt;element name="toCountryNode" type="{}toCountryNodeType" minOccurs="0"/>
 *         &lt;element name="toFunctionNode" type="{}toFunctionNodeType" minOccurs="0"/>
 *         &lt;element name="toGenderNode" type="{}toGenderNodeType" minOccurs="0"/>
 *         &lt;element name="toHomeCountryNode" type="{}toHomeCountryNodeType" minOccurs="0"/>
 *         &lt;element name="toHomeProvinceNode" type="{}toHomeProvinceNodeType" minOccurs="0"/>
 *         &lt;element name="toLanguageNode" type="{}toLanguageNodeType" minOccurs="0"/>
 *         &lt;element name="toProductNode" type="{}toProductNodeType" minOccurs="0"/>
 *         &lt;element name="toProvinceNode" type="{}toProvinceNodeType" minOccurs="0"/>
 *         &lt;element name="toSalutationNode" type="{}toSalutationNodeType" minOccurs="0"/>
 *         &lt;element name="toSingleStatusNode" type="{}toSingleStatusNodeType" minOccurs="0"/>
 *         &lt;element name="toSmtpServerNode" type="{}toSmtpServerNodeType" minOccurs="0"/>
 *         &lt;element name="toSourceNode" type="{}toSourceNodeType" minOccurs="0"/>
 *         &lt;element name="toStatusNode" type="{}toStatusNodeType" minOccurs="0"/>
 *         &lt;element name="toTrialPeriodUnitNode" type="{}toTrialPeriodUnitNodeType" minOccurs="0"/>
 *         &lt;element name="toUserRole" type="{}toUserRoleType" minOccurs="0"/>
 *         &lt;element name="toVisitCountryNode" type="{}toVisitCountryNodeType" minOccurs="0"/>
 *         &lt;element name="toVisitProvinceNode" type="{}toVisitProvinceNodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CRUserType", propOrder = {
    "content"
})
public class CRUserType {

    @XmlElementRefs({
        @XmlElementRef(name = "toVisitCountryNode", type = JAXBElement.class),
        @XmlElementRef(name = "previewDelay", type = JAXBElement.class),
        @XmlElementRef(name = "emailNotificationPopup", type = JAXBElement.class),
        @XmlElementRef(name = "toFunctionNode", type = JAXBElement.class),
        @XmlElementRef(name = "goals", type = JAXBElement.class),
        @XmlElementRef(name = "homeCity", type = JAXBElement.class),
        @XmlElementRef(name = "phoneNumber", type = JAXBElement.class),
        @XmlElementRef(name = "visitAddressUseCompanyVisitAddress", type = JAXBElement.class),
        @XmlElementRef(name = "toTrialPeriodUnitNode", type = JAXBElement.class),
        @XmlElementRef(name = "jobTitle", type = JAXBElement.class),
        @XmlElementRef(name = "addressUseCompanyMailingAddress", type = JAXBElement.class),
        @XmlElementRef(name = "homePostalCode", type = JAXBElement.class),
        @XmlElementRef(name = "userName", type = JAXBElement.class),
        @XmlElementRef(name = "userID", type = JAXBElement.class),
        @XmlElementRef(name = "toSmtpServerNode", type = JAXBElement.class),
        @XmlElementRef(name = "deleted", type = JAXBElement.class),
        @XmlElementRef(name = "additionalInfo", type = JAXBElement.class),
        @XmlElementRef(name = "creationDate", type = JAXBElement.class),
        @XmlElementRef(name = "homeStreet", type = JAXBElement.class),
        @XmlElementRef(name = "password", type = JAXBElement.class),
        @XmlElementRef(name = "homeNumber", type = JAXBElement.class),
        @XmlElementRef(name = "birthDate", type = JAXBElement.class),
        @XmlElementRef(name = "lastContactDate", type = JAXBElement.class),
        @XmlElementRef(name = "toProvinceNode", type = JAXBElement.class),
        @XmlElementRef(name = "isEmailInConfidential", type = JAXBElement.class),
        @XmlElementRef(name = "toVisitProvinceNode", type = JAXBElement.class),
        @XmlElementRef(name = "toGenderNode", type = JAXBElement.class),
        @XmlElementRef(name = "isNewUser", type = JAXBElement.class),
        @XmlElementRef(name = "toSourceNode", type = JAXBElement.class),
        @XmlElementRef(name = "firstName", type = JAXBElement.class),
        @XmlElementRef(name = "toHomeProvinceNode", type = JAXBElement.class),
        @XmlElementRef(name = "userBonuses", type = JAXBElement.class),
        @XmlElementRef(name = "forwardEmail", type = JAXBElement.class),
        @XmlElementRef(name = "toProductNode", type = JAXBElement.class),
        @XmlElementRef(name = "modificationDate", type = JAXBElement.class),
        @XmlElementRef(name = "toCountryNode", type = JAXBElement.class),
        @XmlElementRef(name = "isMasterUser", type = JAXBElement.class),
        @XmlElementRef(name = "isActive", type = JAXBElement.class),
        @XmlElementRef(name = "isTokenRoadActive", type = JAXBElement.class),
        @XmlElementRef(name = "modifiedBy", type = JAXBElement.class),
        @XmlElementRef(name = "initials", type = JAXBElement.class),
        @XmlElementRef(name = "isLoginBlocked", type = JAXBElement.class),
        @XmlElementRef(name = "isTbaActive", type = JAXBElement.class),
        @XmlElementRef(name = "mailboxFlags", type = JAXBElement.class),
        @XmlElementRef(name = "toSingleStatusNode", type = JAXBElement.class),
        @XmlElementRef(name = "toSalutationNode", type = JAXBElement.class),
        @XmlElementRef(name = "isEmailOutConfidential", type = JAXBElement.class),
        @XmlElementRef(name = "lastName", type = JAXBElement.class),
        @XmlElementRef(name = "mailboxSettings", type = JAXBElement.class),
        @XmlElementRef(name = "toUserRole", type = JAXBElement.class),
        @XmlElementRef(name = "mobileNumber", type = JAXBElement.class),
        @XmlElementRef(name = "wantsCookie", type = JAXBElement.class),
        @XmlElementRef(name = "isTokenWorkActive", type = JAXBElement.class),
        @XmlElementRef(name = "isTokenHomeActive", type = JAXBElement.class),
        @XmlElementRef(name = "toLanguageNode", type = JAXBElement.class),
        @XmlElementRef(name = "toHomeCountryNode", type = JAXBElement.class),
        @XmlElementRef(name = "toStatusNode", type = JAXBElement.class),
        @XmlElementRef(name = "emailAddressPrivate", type = JAXBElement.class),
        @XmlElementRef(name = "homeFullAddress", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ToVisitCountryNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ToFunctionNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link GoalsType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ToTrialPeriodUnitNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ToSmtpServerNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link AdditionalInfoType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ToProvinceNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ToVisitProvinceNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link ToGenderNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ToSourceNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ToHomeProvinceNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link UserBonusesType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ToProductNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ToCountryNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ModifiedByType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ToSingleStatusNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link ToSalutationNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link MailboxSettingsType }{@code >}
     * {@link JAXBElement }{@code <}{@link ToUserRoleType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ToLanguageNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link ToHomeCountryNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link ToStatusNodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
